dist: trusty
sudo: required
language: cpp 

services:
  - mysql

notifications:
  email:
    recipients:
      - 0f9234u9f0jw3@gmx.de
    on_success: always
    on_failure: always

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install libboost-all-dev
  - sudo apt-get -y install libmysqlclient-dev

script:
  - bash ./scripts/ci/travis/setup_restbed.sh
  - bash ./scripts/ci/travis/setup_rapidjson.sh
  - bash ./scripts/ci/travis/setup_gsl.sh
  - bash ./scripts/ci/travis/setup_doctest.sh
  - bash ./scripts/ci/travis/setup_mysql_database.sh
  - sudo bash ./scripts/ci/travis/setup_cppdb.sh
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake -DCMAKE_BUILD_TYPE=Debug -DCI_SERVER=travis . # generate build scripts
  - cmake --build . -- -j2                                                                   # build using 2 threads
  - ./cpp_rest &                                                                             # launch the application
  - ctest --verbose .                                                                        # run the tests
  - bash ./scripts/ci/travis/print_file_if_exists.sh ./example_rest_api_restbed.log
  - bash ./scripts/ci/travis/print_file_if_exists.sh ./cpp_rest.log
  - bash ./scripts/ci/travis/print_file_if_exists.sh ./another_rest_api_restbed.log
    
