dist: trusty  # use Ubuntu trusty distro
sudo: true    # use sudo
language: cpp # use C++ 

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script:
  - sh ./scripts/ci/travis/setup_restbed.sh
  - sh ./scripts/ci/travis/setup_nlohmann_json.sh
  - sudo sh ./scripts/ci/travis/setup_boost.sh
  - sh ./scripts/ci/travis/setup_gsl.sh
  - sh ./scripts/ci/travis/setup_doctest.sh
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake . # generate build scripts
  - cmake --build . -- -j2                       # build using 2 threads
# TODO: The application may need to be started in a child process before running the tests, assuming that there are tests testing the REST API/s.
  - ctest --verbose .                            # run the tests

