image:
  - Visual Studio 2015
clone_folder: C:\cpp_rest

services:
  - mysql
  
environment:
  MYSQL_DRIVER_URL: https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.11-src.zip
  MYSQL_DRIVER_ARCHIVE: mysql-connector-c-6.1.11-src.zip
  MYSQL_DRIVER_NAME: mysql-connector-c-6.1.11-src
  
install:
  - cinst curl 7zip # mysql-connector mysql.workbench mysql.utilities mysql.odbc
    
  # install mysql driver
  - cd %USERPROFILE%
  - curl -kLO %MYSQL_DRIVER_URL%
  - 7z x %MYSQL_DRIVER_ARCHIVE% >nul
  - mkdir %USERPROFILE%\%MYSQL_DRIVER_NAME%\build
  - cd %USERPROFILE%\%MYSQL_DRIVER_NAME%\build
  - cmake -G "Visual Studio 14" ..
  - msbuild /m /p:Configuration=Release LibMySQL.sln
  - curl -kLO https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.11-win32.zip
  - 7z x mysql-connector-c-6.1.11-win32.zip >nul
  - xcopy /s mysql-connector-c-6.1.11-win32/include %USERPROFILE%\%MYSQL_DRIVER_NAME%\include /Y
  #- dir %USERPROFILE%\%MYSQL_DRIVER_NAME%\build\libmysql
  #- dir %USERPROFILE%\%MYSQL_DRIVER_NAME%\build\libmysql\Release  
  # - set "PATH=%PATH%;%USERPROFILE%\%MYSQL_DRIVER_NAME%\lib"
  # - set "PATH=%PATH%;%USERPROFILE%\%MYSQL_DRIVER_NAME%\lib\vs14"
    
#    irectory of C:\Users\appveyor\mysql-connector-c-6.1.11-src\build\libmysql\Release
#10/18/2017  01:15 PM    <DIR>          .
#10/18/2017  01:15 PM    <DIR>          ..
#10/18/2017  01:15 PM           257,046 clientlib.lib
#10/18/2017  01:15 PM         3,908,608 libmysql.dll
#10/18/2017  01:15 PM            16,811 libmysql.exp
#10/18/2017  01:15 PM            28,714 libmysql.lib
#10/18/2017  01:15 PM           102,400 libmysql_api_test.exe
#10/18/2017  01:15 PM         5,943,220 mysqlclient.lib
    
build_script:
- ps: >-
      $sqlScript = [IO.File]::ReadAllText("C:\cpp_rest\scripts\sql\setup_db.sql")
    
      $env:MYSQL_PWD="Password12!"
      
      $cmd = '"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -e "$sqlScript" --user=root'
      
      iex "& $cmd"

- cmd: >-
    cd C:\cpp_rest
    
    C:\cpp_rest\scripts\ci\appveyor\setup_doctest.bat
    
    C:\cpp_rest\scripts\ci\appveyor\setup_gsl.bat
    
    C:\cpp_rest\scripts\ci\appveyor\setup_rapidjson.bat
    
    C:\cpp_rest\scripts\ci\appveyor\setup_restbed.bat 
    
    C:\cpp_rest\scripts\ci\appveyor\setup_cppdb.bat
                        
    mkdir C:\cpp_rest\build
    
    cd C:\cpp_rest
            
    cmake -DCMAKE_BUILD_TYPE=Release -DCI_SERVER=appveyor -G "Visual Studio 14" C:\cpp_rest
    
    cmake --build C:\cpp_rest --config "Release"
        
    msbuild /m /p:Configuration=Release C:\cpp_rest\windows_launch_in_new_process_application\launchApplication.sln
              
test: on
test_script:
  - cmd: >-
      dir C:\cpp_rest\windows_launch_in_new_process_application\x64\Release
          
      ctest --verbose C:\cpp_rest
      
      if exist C:\cpp_rest\example_rest_api_restbed.log type C:\cpp_rest\example_rest_api_restbed.log
      
      if exist C:\cpp_rest\cpp_rest.log type C:\cpp_rest\cpp_rest.log      
      
      if exist C:\cpp_rest\another_rest_api_restbed.log type C:\cpp_rest\another_rest_api_restbed.log
      
