image:
  - Visual Studio 2017
clone_folder: C:\cpp_rest
build_script:
- cmd: >-
    cd C:\cpp_rest
    
    C:\cpp_rest\scripts\ci\appveyor\setup_doctest.bat
    
    C:\cpp_rest\scripts\ci\appveyor\setup_gsl.bat
    
    C:\cpp_rest\scripts\ci\appveyor\setup_rapidjson.bat
    
    C:\cpp_rest\scripts\ci\appveyor\setup_restbed.bat 
        
    dir C:\Users\appveyor\restbed\build
                
    mkdir C:\cpp_rest\build
            
    cmake C:\cpp_rest\build -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 15" C:\cpp_rest
    
    cmake --build C:\cpp_rest --config "Debug"
        
    ctest --verbose C:\cpp_rest
      
