image:
  - Visual Studio 2015
clone_folder: C:\cpp_rest
build_script:
- cmd: >-
    cd C:\cpp_rest
    
    C:\cpp_rest\scripts\ci\appveyor\setup_doctest.bat
    
    C:\cpp_rest\scripts\ci\appveyor\setup_gsl.bat
    
    C:\cpp_rest\scripts\ci\appveyor\setup_rapidjson.bat
    
    C:\cpp_rest\scripts\ci\appveyor\setup_restbed.bat 
                        
    mkdir C:\cpp_rest\build
            
    cmake C:\cpp_rest\build -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 14" C:\cpp_rest
    
    cmake --build C:\cpp_rest --config "Debug"
              
test: on
test_script:
  - cmd: >-
      start cmd.exe @cmd /k "C:\cpp_rest\build\cpp_rest"
  
      ctest --verbose C:\cpp_rest
      
