image:
  - Visual Studio 2015
clone_folder: C:\cpp_rest
build_script:
- cmd: >-
    scripts/ci/appveyor/setup_doctest.bat
    
    scripts/ci/appveyor/setup_gsl.bat
    
    scripts/ci/appveyor/setup_nlohmann_json.bat
    
    scripts/ci/appveyor/setup_restbed.bat
    
    mkdir build    
    
    cd build    
    
    cmake C:\cpp_rest -G "Visual Studio 14" . # Generate build scripts
    
    cmake --build . --config "Debug"          # Build application
        
    ctest --verbose .                         # Run the tests.
      
